[versions]

kotlin = "1.9.21"
agp = "8.2.0"
compose = "1.5.11"
androidx-activityCompose = "1.8.1"
composeImageLoader = "1.6.4"
napier = "2.6.1"
buildConfig = "4.1.2"
kotlinx-coroutines = "1.7.3"
ktor = "2.3.6"
koin = "3.5.0"
kotlinx-serialization = "1.6.0"
kotlinx-datetime = "0.4.1"
multiplatformSettings = "1.0.0"
windowSize = "0.3.1"
kstore = "0.6.0"
moko-version = "0.23.0"
slf4j = "1.7.36"
decompose-reimaginate = "0.0.4.1"
decompose = "2.2.0-compose-experimental"
essenty = "1.3.0"

[libraries]

moko = { group = "dev.icerock.moko", name = "resources", version.ref = "moko-version" }
moko-compose = { group = "dev.icerock.moko", name = "resources-compose", version.ref = "moko-version" }

koin = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
slf4j-nop = { group = "org.slf4j", name = "slf4j-nop", version.ref = "slf4j" }

essenty = { group = "com.arkivanov.essenty", name = "lifecycle", version.ref = "essenty" }
androidx-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activityCompose" }
compose-uitooling = { group = "androidx.compose.ui", name = "ui-tooling" }

windowSize = { group = "dev.chrisbanes.material3", name = "material3-window-size-class-multiplatform", version.ref = "windowSize" }

decompose-base = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-jetbrains-compose = { group = "com.arkivanov.decompose", name = "extensions-compose-jetbrains", version.ref = "decompose" }

composeImageLoader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "composeImageLoader" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-content-negotiaion = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
multiplatformSettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatformSettingsNoArg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
kstore = { module = "io.github.xxfast:kstore", version.ref = "kstore" }

[bundles]

multiplatformSettings = ["multiplatformSettings", "multiplatformSettingsNoArg"]
ktor = ["ktor-client", "ktor-core", "ktor-logging", "ktor-content-negotiaion", "ktor-serialization-json", "slf4j-nop"]
koin = ["koin"]
decompose = ["decompose-base", "decompose-jetbrains-compose", ]
moko = ["moko", "moko-compose"]

[plugins]

moko-multiplatform-resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko-version" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
