[versions]

kotlin = "1.9.0"
agp = "8.1.0"
compose = "1.4.3"
androidx-appcompat = "1.6.1"
androidx-activityCompose = "1.7.2"
compose-uitooling = "1.5.1"
libres = "1.1.8"
proguardGradle = "7.2.2"
resourcesGenerator = "0.23.0"
voyager = "1.0.0-rc06"
accomp = "0.33.1-alpha"
composeImageLoader = "1.6.4"
napier = "2.6.1"
buildConfig = "4.1.1"
kotlinx-coroutines = "1.7.3"
ktor = "2.3.4"
koin = "3.4.3"
compose-bom = "2023.09.00"
kotlinx-serialization = "1.5.1"
kotlinx-datetime = "0.4.0"
multiplatformSettings = "1.0.0"
windowSize = "0.3.1"
kstore = "0.6.0"
moko-version = "0.23.0"
slf4j = "1.7.36"

[libraries]

moko = { group = "dev.icerock.moko", name = "resources", version.ref = "moko-version" }
moko-compose = { group = "dev.icerock.moko", name = "resources-compose", version.ref = "moko-version" }
moko-resources-generator = { module = "dev.icerock.moko:resources-generator", version.ref = "resourcesGenerator" }

koin = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
slf4j-nop = { group = "org.slf4j", name = "slf4j-nop", version.ref = "slf4j" }

material3 = { group = "androidx.compose.material3", name = "material3" }
materialIconExt = { group = "androidx.compose.material", name = "material-icons-extended" }
composeMaterialIcons = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat" }
androidx-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activityCompose" }
compose-uitooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-uitooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

proguard-gradle = { module = "com.guardsquare:proguard-gradle", version.ref = "proguardGradle" }
windowSize = { group = "dev.chrisbanes.material3", name = "material3-window-size-class-multiplatform", version.ref = "windowSize" }

libres = { module = "io.github.skeptick.libres:libres-compose", version.ref = "libres" }
voyager-navigator = { group = "cafe.adriel.voyager", name = "voyager-navigator", version.ref = "voyager" }
voyager-navigator-sheet-navigator = { group = "cafe.adriel.voyager", name = "voyager-bottom-sheet-navigator", version.ref = "voyager" }
composeImageLoader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "composeImageLoader" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-content-negotiaion = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
multiplatformSettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatformSettingsNoArg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
kstore = { module = "io.github.xxfast:kstore", version.ref = "kstore" }

accomSystemUI = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accomp" }
androidx-foundation-android = { group = "androidx.compose.foundation", name = "foundation-android", version = "1.5.1" }

[bundles]

compose = ["compose-uitooling-preview", "compose-uitooling", "composeImageLoader", "composeMaterialIcons"]
multiplatformSettings = ["multiplatformSettings", "multiplatformSettingsNoArg"]
ktor = ["ktor-client", "ktor-core", "ktor-logging", "ktor-content-negotiaion", "ktor-serialization-json"]
koin = ["koin"]
moko = ["moko", "moko-compose"]
voyager = ["voyager-navigator"]

[plugins]

moko-multiplatform-resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko-version" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
libres = { id = "io.github.skeptick.libres", version.ref = "libres" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
