name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Setup variables
        run: |
          touch local.properties
          echo "clientId=${{secrets.CLIENT_ID}}" > local.properties
          echo "clientSecret=${{secrets.CLIENT_SECRET}}" > local.properties
          echo "redirectURI=${{secrets.REDIRECT_URI}}" > local.properties
          echo "domain={{secrets.CLIENT_DOMAIN}}" > local.properties
          echo "userAgent=${{secrets.USER_AGENT}}" > local.properties
      - name: Build linux apps
        run: |
          ./gradlew packageReleaseRpm
          ./gradlew packageReleaseDeb
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: nextshiki_rpm.rpm
          path: composeApp/build/compose/binaries/main/app/com.rcl.nextshiki.desktopApp/com.rcl.nextshiki.desktopApp.rpm