name: CI

env:
  clientId: ${{secrets.CLIENT_ID}}
  redirectURI: ${{secrets.REDIRECT_URI}}
  clientSecret: ${{secrets.CLIENT_SECRET}}
  domain: ${{secrets.CLIENT_DOMAIN}}
  userAgent: ${{secrets.USER_AGENT}}

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build linux apps
        run: |
          ./gradlew packageReleaseRpm
          ./gradlew packageReleaseDeb
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: nextshiki_rpm.rpm
          path: composeApp/build/compose/binaries/main/app/com.rcl.nextshiki.desktopApp/com.rcl.nextshiki.desktopApp.rpm