name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      #- name: Checkout keystore repo
      #  uses: actions/checkout@v3
      #  with:
      #    repository: ${{ secrets.KEY_REPO }}
      #    token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
      #    path: app/keystore
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Setup moko resources
        run: ./gradlew generateMRcommonMain
      - name: Build Linux Apps
        run: |
          ./gradlew test
          ./gradlew packageReleaseRpm
          ./gradlew packageReleaseDeb
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: nextshiki_rpm.rpm
          path: composeApp/build/compose/binaries/main/app/com.rcl.nextshiki.desktopApp/com.rcl.nextshiki.desktopApp.rpm
      #- name: Upload AAB Bundle
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: app-release.aab
      #    path: app/build/outputs/bundle/release/app-release.aab