name: CI

env:
  clientId: ${{secrets.CLIENT_ID}}
  redirectURI: ${{secrets.REDIRECT_URI}}
  clientSecret: ${{secrets.CLIENT_SECRET}}
  domain: ${{secrets.CLIENT_DOMAIN}}
  userAgent: ${{secrets.USER_AGENT}}
  scope: ${{secrets.SCOPE}}

  clientIDDesk: ${{secrets.CLIENT_ID_DESK}}
  clientSecretDesk: ${{secrets.CLIENT_SECRET_DESK}}
  redirectURIDesk: ${{secrets.REDIRECT_URI_DESK}}
  scopeDesk: ${{secrets.SCOPE_DESK}}
  userAgentDesk: ${{secrets.USER_AGENT_DESK}}

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Setup resources
        run: ./gradlew generateMR
      - name: Build linux apps
        run: |
          ./gradlew packageReleaseAppImage
      - name: Upload linux builds
        uses: actions/upload-artifact@v4.3.0
        with:
          name: Nextshiki.desktop
          path: composeApp/build/compose/binaries/main-release/app/Nextshiki/bin/*
      - name: Build android app
        run: |
          ./gradlew assemble
      - name: Upload android builds
        uses: actions/upload-artifact@v4.3.0
        with:
          name: Nextshiki.apk
          path: composeApp/build/outputs/apk/release/*.apk
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup resources
        run: ./gradle.bat generateMR
      - name: Build Windows apps
        run: |
          ./gradle.bat packageReleaseMsi
      - name: Upload linux builds
        uses: actions/upload-artifact@v4.3.0
        with:
          name: Nextshiki.msi
          path: composeApp/build/compose/binaries/main-release/msi/*.msi