name: CI

env:
  clientId: ${{secrets.CLIENT_ID}}
  redirectURI: ${{secrets.REDIRECT_URI}}
  clientSecret: ${{secrets.CLIENT_SECRET}}
  domain: ${{secrets.CLIENT_DOMAIN}}
  userAgent: ${{secrets.USER_AGENT}}
  scope: ${{secrets.SCOPE}}

  clientIDDesk: ${{secrets.CLIENT_ID_DESK}}
  clientSecretDesk: ${{secrets.CLIENT_SECRET_DESK}}
  redirectURIDesk: ${{secrets.REDIRECT_URI_DESK}}
  scopeDesk: ${{secrets.SCOPE_DESK}}
  userAgentDesk: ${{secrets.USER_AGENT_DESK}}

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build linux apps
        run: |
          ./gradlew packageReleaseAppImage
      - name: Upload linux builds
        uses: actions/upload-artifact@v3
        with:
          name: nextshiki_desktop_appimage.desktopApp
          path: composeApp/build/compose/binaries/main-release/app
      - name: Build android app
        run: |
          ./gradlew assembleReleaseWithLogger
      - name: Upload android builds
        uses: actions/upload-artifact@v3
        with:
          name: nextshiki_android_RWL.apk
          path: composeApp/build/outputs/apk/composeApp-releaseWithLogger.apk